# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
[main.params]
icon = "home"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/lovelock"

[social.params]
icon = "brand-github"

[[social]]
identifier = "weibo"
name = "Weibo"
url = "https://weibo.com/u/7951512891"

[social.params]
icon = "brand-weibo"
